### ISSUE TITLE
Getting started with OpenGL and Go

### ISSUE THREAD

**Issue by drgomesp** [drgomesp/.dev#1]
...

**Comment by drgomesp** [comment]
**2020-05-31 Review**

- Added comment section
- Made sure the code example works on a modern build
- Updated image references

**Comment by JennaBarbara** [comment]
This is a nice intro, thanks!

**Comment by dbalciunas** [comment]
I tried to compile the exemple in vscode and got the following errors:
PS X:\Projects\Go> go build .\main.go
# command-line-arguments
D:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld:  cannot find  -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld:  cannot find  -lmingw32
collect2: error: ld devolvió el estado de salida 1
